name: Auto Assign

on:
  issue_comment:
    types: [created]

jobs:
  assign_issues:
    runs-on: ubuntu-latest
    steps:
      - name: Check for issue assign command
        id: check_assign
        run: echo ${{ github.event.comment.body }} > comment.txt

      - name: Read comment file
        id: read_comment
        run: |
          COMMENT=$(cat comment.txt)
          echo "Comment: $COMMENT"
          echo "::set-output name=comment::$COMMENT"

      - name: Assign Issue
        if: startsWith(steps.read_comment.outputs.comment, '/assign')
        run: |
          USER=$(echo ${{ github.event.comment.user.login }})
          echo "Assigning issue to @$USER"
          gh issue assign $USER
