name: Auto Assign

on:
  issue_comment:
    types: [created]

jobs:
  assign_issues:
    runs-on: ubuntu-latest
    steps:
      - name: Check for issue assign command
        id: check_assign
        run: echo "::set-output name=assign::$(echo ${{ github.event.comment.body }} | grep -o '/assign')"
        
      - name: Assign Issue
        if: steps.check_assign.outputs.assign
        run: |
          # Extract the commenter's username from the comment
          USER=$(echo ${{ github.event.comment.user.login }})

          # Assign the issue to the commenter
          echo "Assigning issue to @$USER"
          gh issue assign $USER
